### ISSUE TITLE
Blocks without comments are ignored

### ISSUE THREAD

**Issue by mongrelion** [bittersweet/notes#4]
I have the following notes file:
```
# Multiple machines
config.vm.define "foo" do |machine|
end

config.vm.define "bar" do |machine|
end
```

And when I print it out with `notes`, it ignores the block that has no precedent comment line (the second ruby block).

Check out the screenshot attached

![e42ln](https://cloud.githubusercontent.com/assets/196122/16228188/c9d2109c-37b5-11e6-885b-c979fd88990a.png)

**Comment by bittersweet** [comment]
I'll take a look at the parsing code, newlines in explanations weren't supported yet. 

In the meantime you can work around it by removing the newlines, or adding another note in the file ;)

**Comment by bittersweet** [comment]
I've pushed some commits for this to https://github.com/bittersweet/notes/tree/support_newlines, please let me know how that works out for you. I've tested it with your example and it looks good, but curious if you have more situations.

**Comment by mongrelion** [comment]
@bittersweet I tried this out and it is working properly :+1:
When will you have it merged?

**Comment by bittersweet** [comment]
Get it while it's hot https://github.com/bittersweet/notes/releases/tag/v0.7.0

Thanks for the bug report ✌️
